CLUSTER_ADD_GROUP_EVENT = "ON_CLUSTER_ADD_GROUP"
CLUSTER_DELETE_GROUP_EVENT = "ON_CLUSTER_DELETE_GROUP"
CLUSTER_COMMIT_GROUP_EVENT = "ON_CLUSTER_COMMIT_GROUP"
CLUSTER_ROLLBACK_GROUP_EVENT = "ON_CLUSTER_ROLLBACK_GROUP"